/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.pm2.socialWins;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Test test = new Test();
        test.test();
    }
}
